; PrintGuardian Latvian translations for Tauri-specific NSIS strings.
; NSIS itself provides the standard Latvian MUI strings; Tauri does not
; currently ship Latvian translations for its additional installer labels.

LangString addOrReinstall ${LANG_LATVIAN} "Pievienot / pārinstalēt komponentus"
LangString alreadyInstalled ${LANG_LATVIAN} "Jau instalēts"
LangString alreadyInstalledLong ${LANG_LATVIAN} "${PRODUCTNAME} ${VERSION} jau ir instalēts. Izvēlies veicamo darbību un spied Tālāk, lai turpinātu."
LangString appRunning ${LANG_LATVIAN} "{{product_name}} pašlaik darbojas. Aizver programmu un mēģini vēlreiz."
LangString appRunningOkKill ${LANG_LATVIAN} "{{product_name}} pašlaik darbojas.$\nNospied Labi, lai programmu aizvērtu."
LangString chooseMaintenanceOption ${LANG_LATVIAN} "Izvēlies veicamo apkopes darbību."
LangString choowHowToInstall ${LANG_LATVIAN} "Izvēlies, kā instalēt ${PRODUCTNAME}."
LangString createDesktop ${LANG_LATVIAN} "Izveidot saīsni darbvirsmā"
LangString dontUninstall ${LANG_LATVIAN} "Neatinstalēt"
LangString dontUninstallDowngrade ${LANG_LATVIAN} "Neatinstalēt (šis instalators neatļauj pazemināt versiju bez atinstalēšanas)"
LangString failedToKillApp ${LANG_LATVIAN} "Neizdevās aizvērt {{product_name}}. Aizver programmu un mēģini vēlreiz."
LangString installingWebview2 ${LANG_LATVIAN} "Instalē Microsoft WebView2..."
LangString newerVersionInstalled ${LANG_LATVIAN} "Datorā jau ir instalēta jaunāka ${PRODUCTNAME} versija. Vecākas versijas instalēšana nav ieteicama. Ja tiešām vēlies instalēt vecāku versiju, vispirms ieteicams atinstalēt pašreizējo. Izvēlies veicamo darbību un spied Tālāk."
LangString older ${LANG_LATVIAN} "vecāka"
LangString olderOrUnknownVersionInstalled ${LANG_LATVIAN} "Datorā ir instalēta $R4 ${PRODUCTNAME} versija. Pirms turpināšanas ieteicams atinstalēt pašreizējo versiju. Izvēlies veicamo darbību un spied Tālāk."
LangString silentDowngrades ${LANG_LATVIAN} "Šis instalators neatļauj automātisku versijas pazemināšanu. Izmanto grafisko instalatoru.$\n"
LangString unableToUninstall ${LANG_LATVIAN} "Neizdevās atinstalēt programmu."
LangString uninstallApp ${LANG_LATVIAN} "Atinstalēt ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_LATVIAN} "Atinstalēt pirms instalēšanas"
LangString unknown ${LANG_LATVIAN} "nezināma"
LangString webview2AbortError ${LANG_LATVIAN} "Neizdevās instalēt Microsoft WebView2. Bez tā lietotni nevar palaist. Restartē instalatoru un mēģini vēlreiz."
LangString webview2DownloadError ${LANG_LATVIAN} "Kļūda: neizdevās lejupielādēt Microsoft WebView2 — $0"
LangString webview2DownloadSuccess ${LANG_LATVIAN} "Microsoft WebView2 instalators ir lejupielādēts."
LangString webview2Downloading ${LANG_LATVIAN} "Lejupielādē Microsoft WebView2 instalatoru..."
LangString webview2InstallError ${LANG_LATVIAN} "Kļūda: Microsoft WebView2 instalēšana neizdevās (kods $1)"
LangString webview2InstallSuccess ${LANG_LATVIAN} "Microsoft WebView2 ir veiksmīgi instalēts."
LangString deleteAppData ${LANG_LATVIAN} "Dzēst arī PrintGuardian lietotnes datus un iestatījumus"
